# Simple workflow for deploying static content to GitHub Pages
name: GH Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        env:
          MOVIES_APP_OMBD_API_URL: ${{ secrets.MOVIES_APP_OMBD_API_URL }}
          MOVIES_APP_OMDB_API_KEY: ${{ secrets.MOVIES_APP_OMDB_API_KEY }}
        uses: actions/checkout@v3
      - name: Set up Node
        env:
          MOVIES_APP_OMBD_API_URL: ${{ secrets.MOVIES_APP_OMBD_API_URL }}
          MOVIES_APP_OMDB_API_KEY: ${{ secrets.MOVIES_APP_OMDB_API_KEY }}
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        env:
          MOVIES_APP_OMBD_API_URL: ${{ secrets.MOVIES_APP_OMBD_API_URL }}
          MOVIES_APP_OMDB_API_KEY: ${{ secrets.MOVIES_APP_OMDB_API_KEY }}
        run: npm install
      - name: Build
        env:
          MOVIES_APP_OMBD_API_URL: ${{ secrets.MOVIES_APP_OMBD_API_URL }}
          MOVIES_APP_OMDB_API_KEY: ${{ secrets.MOVIES_APP_OMDB_API_KEY }}
        run: npm run build-vite
      - name: Setup Pages
        env:
          MOVIES_APP_OMBD_API_URL: ${{ secrets.MOVIES_APP_OMBD_API_URL }}
          MOVIES_APP_OMDB_API_KEY: ${{ secrets.MOVIES_APP_OMDB_API_KEY }}
        uses: actions/configure-pages@v3
      - name: Upload artifact
        env:
          MOVIES_APP_OMBD_API_URL: ${{ secrets.MOVIES_APP_OMBD_API_URL }}
          MOVIES_APP_OMDB_API_KEY: ${{ secrets.MOVIES_APP_OMDB_API_KEY }}
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload dist repository
          path: './dist'
      - name: Deploy to GitHub Pages
        env:
          MOVIES_APP_OMBD_API_URL: ${{ secrets.MOVIES_APP_OMBD_API_URL }}
          MOVIES_APP_OMDB_API_KEY: ${{ secrets.MOVIES_APP_OMDB_API_KEY }}
        id: deployment
        uses: actions/deploy-pages@v1
